FROM maven:3.9.0-eclipse-temurin-17 as builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src/ ./src/
RUN mvn clean package -DskipTests=true

FROM eclipse-temurin:17-jdk-alpine as prod

# INSTALL FONTS
RUN apk update && apk add --no-cache msttcorefonts-installer fontconfig \
    && update-ms-fonts \
    && fc-cache -f -v \

RUN apk update && apk add --no-cache fontconfig \
    && apk add --no-cache ttf-dejavu ttf-droid ttf-freefont ttf-liberation \
    && fc-cache -f -v

# CONFIGURE TIMEZONE
RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && echo "America/Sao_Paulo" > /etc/timezone \
    && apk del tzdata

COPY --from=builder /app/target/*.jar /app.jar

# SERVER AND APPLICATION CONFIGURATIONS ARGS
ARG SPRING_PROFILES_ACTIVE
ARG PORT
ARG APP_VERSION
ARG APP_SERVER_URL
ARG APP_SECRET
ARG APP_ENVIRONMENT
ARG APP_EMAIL_SENDER
ARG APP_EMAIL_PASSWORD
ARG SPRING_APPLICATION_NAME
# DATABASE CONFIGURATIONS ARGS
ARG CONNECTION_POOL_SIZE
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_JPA_SHOW_SQL
# CONFIGURING CACHE
ARG SPRING_DATA_REDIS_URL
ARG SPRING_DATA_REDIS_HOST
ARG SPRING_DATA_REDIS_DATABASE
ARG SPRING_DATA_REDIS_USERNAME
ARG SPRING_DATA_REDIS_PASSWORD
ARG SPRING_DATA_REDIS_PORT


# SERVER AND APPLICATION CONFIGURATIONS
WORKDIR /app
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV PORT=${PORT}
ENV APP_VERSION=${APP_VERSION}
ENV APP_SERVER_URL=${APP_SERVER_URL}
ENV APP_SECRET=${APP_SECRET}
ENV APP_ENVIRONMENT=${APP_ENVIRONMENT}
ENV APP_EMAIL_SENDER=${APP_EMAIL_SENDER}
ENV APP_EMAIL_PASSWORD=${APP_EMAIL_PASSWORD}
# DATABASE CONFIGURATIONS
ENV CONNECTION_POOL_SIZE=${CONNECTION_POOL_SIZE}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
# CONFIGURING CACHE
ENV SPRING_DATA_REDIS_URL=${SPRING_DATA_REDIS_URL}
ENV SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
ENV SPRING_DATA_REDIS_DATABASE=${SPRING_DATA_REDIS_DATABASE}
ENV SPRING_DATA_REDIS_USERNAME=${SPRING_DATA_REDIS_USERNAME}
ENV SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
ENV SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}

# EXPOSE THE PORT
EXPOSE ${PORT}
# RUN THE APPLICATION
ENTRYPOINT ["java", "-jar", "/app.jar"]
