name: Run build, tests, sonarqube, docker and deploy

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -DskipTests -Ptest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Maven tests
        run: mvn -B verify -Ptest

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

  qodana:
    runs-on: ubuntu-latest
    needs: test

#    permissions:
#      contents: write
#      pull-requests: write
#      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Download JaCoCo report
        uses: actions/download-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco

#      - name: 'Qodana Scan'
#        uses: JetBrains/qodana-action@v2024.1
#        env:
#          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          project-dir: ./
          results-dir: qodana-report
          project-key: walletwise-api
          baseline-path: target/site/jacoco/jacoco.xml

      - name: Upload Qodana report
        uses: actions/upload-artifact@v2
        with:
          name: qodana-report
          path: qodana-report

  docker:
    runs-on: ubuntu-latest
    needs: test
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}

      - name: Determinate Image tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg SPRING_PROFILES_ACTIVE="${{ vars.SPRING_PROFILES_ACTIVE }}" \
            --build-arg PORT="${{ vars.PORT }}" \
            --build-arg APP_VERSION="${{ env.IMAGE_TAG }}" \
            --build-arg APP_SERVER_URL="${{ vars.APP_SERVER_URL }}" \
            --build-arg APP_SECRET="${{ vars.APP_SECRET }}" \
            --build-arg APP_ENVIRONMENT="${{ vars.APP_ENVIRONMENT }}" \
            --build-arg APP_EMAIL_SENDER="${{ vars.APP_EMAIL_SENDER }}" \
            --build-arg APP_EMAIL_PASSWORD="${{ vars.APP_EMAIL_PASSWORD }}" \
            --build-arg SPRING_APPLICATION_NAME="${{ vars.SPRING_APPLICATION_NAME }}" \
            --build-arg SPRING_DATASOURCE_URL="${{ vars.SPRING_DATASOURCE_URL }}" \
            --build-arg SPRING_DATASOURCE_USERNAME="${{ vars.SPRING_DATASOURCE_USERNAME }}" \
            --build-arg SPRING_DATASOURCE_PASSWORD="${{ vars.SPRING_DATASOURCE_PASSWORD }}" \
            --build-arg SPRING_JPA_SHOW_SQL="${{ vars.SPRING_JPA_SHOW_SQL }}" \
            -t "${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }}" .

      - name: Push Docker image
        run: |
          docker push "${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }}"

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Authenticate Docker to Google Cloud
        run: |
          gcloud auth configure-docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}

      - name: Determine Image tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Determine Application  name
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "SPRING_APPLICATION_NAME=walletwise-api-staging" >> $GITHUB_ENV
          else
            echo "SPRING_APPLICATION_NAME=walletwise-api-production" >> $GITHUB_ENV
          fi

      - name: Pull Docker image
        run: docker pull "${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Tag Docker image
        run: |
          docker tag "${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }}" \
            "gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Push Docker image to GCP
        run: docker push "gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Deploy to GCP Cloud Run
        run: |
          gcloud run deploy ${{ env.SPRING_APPLICATION_NAME }} \
            --image=gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }} \
            --platform=managed --region=southamerica-east1 --allow-unauthenticated --revision-suffix=${{ env.IMAGE_TAG }}

      - name: Remove Docker images
        run: |
          docker rmi "${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }}" \
            "gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.DOCKER_APPLICATION_NAME }}:${{ env.IMAGE_TAG }}"
            